### ISSUE TITLE
Cannot read property 'hideKeyboardAccessoryBar' of undefined in Ripple Emulator

### ISSUE THREAD

**Issue by andycaramba** [driftyco/ionic-plugins-keyboard#18]
Hi. I get the following error when trying to run the ionic app with this plugin in the Ripple emulator. Other plugins do not cause such error.

```
missing exec:Keyboard.hideKeyboardAccessoryBar ripple.js:34331
Array[1]
 ripple.js:34332
TypeError
message: "Cannot read property 'hideKeyboardAccessoryBar' of undefined"
stack: (...)
get stack: function () { [native code] }
set stack: function () { [native code] }
__proto__: Error
 ripple.js:34333
TypeError: Cannot read property 'hideKeyboardAccessoryBar' of undefined
    at module.exports.exec (http://localhost:4400/ripple/assets/ripple.js:34328:30)
    at Function.Keyboard.hideKeyboardAccessoryBar (http://localhost:4400/plugins/com.ionic.keyboard/www/keyboard.js:10:5)
    at http://localhost:4400/js/app.js:14:42
    at Array.<anonymous> (http://localhost:4400/vendor/ionic/js/ionic.bundle.js:36865:19)
    at onPlatformReady (http://localhost:4400/vendor/ionic/js/ionic.bundle.js:2329:24)
    at Channel.fire (http://localhost:4400/cordova.js:760:23)
    at http://localhost:4400/cordova.js:223:49 ripple.js:34334
Keyboard ripple.js:50497
hideKeyboardAccessoryBar ripple.js:50498
```

I use autogenerated code on app run

``` javascript
.run(function ($ionicPlatform) {
        $ionicPlatform.ready(function () {
            // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
            // for form inputs)
            if (window.cordova && window.cordova.plugins.Keyboard) {
                cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
            }
            if (window.StatusBar) {
                // org.apache.cordova.statusbar required
                StatusBar.styleDefault();
            }
        });
    })
```

**Comment by wocar** [comment]
@tlancina Thank you so much,

**Comment by rodrigobotti** [comment]
I know it's an old post but here's my solution to hide ripple's popup entirely:
```javascript
var dialogBody = parent.document.getElementById("exec-dialog");
var overlay = parent.document.querySelector(".ui-widget-overlay");
var ngDialog = angular.element(dialogBody.parentElement);
var ngOverlay = angular.element(overlay);
var hideRules = { "height": "0px", "width": "0px", "display": "none" };
ngDialog.css(hideRules); // hide annoying popup
ngOverlay.css(hideRules); // hide annoying popup's backdrop
```
PS: I ommited the `if` checks for the sake of demostration.

**Comment by nsw2206** [comment]
Hi,
where exactly does this code go? I've tried the start of 
$ionicPlatform.ready(function() { 
in app.js but still the popup.. :(
and where were the if checks omitted? 
thanks in advance

**Comment by rodrigobotti** [comment]
Hi @nsw2206.To address you questions: 
- `where were the if checks ommited ?`
  - after getting the reference to ripple's dialog's DOM nodes I didn't checkto see if they were actually not undefined (and they will be undefined in a real device or device emulator) such as adding `if (!dialogBody) return;` to the code above.
   - what I actualy end up using is a function to check if the code is running in a ripple simulated environment so I don't actually have to manually check if each dialog node I'm referencing actually exists
- `where exactly does this code go?`
  - I put it in the callback of `$ionicPlatform.ready` just like yourself. I didi one thing different though: executed the code inside a `$timeout` with 0ms of interval ('trick' to schedule the function's execution in the event bus)
- In the end I have something like this:

```javascript
// I define this as a global function since I use it in other places
function isRunningInRipple(){
   // in device all url's in the webview are 'file:// ... '
   return document.URL.indexOf('http://') >= 0 || document.URL.indexOf('https://') >= 0;
}

var app =  angular.module('myApp', [ ' ...dependencies...' ]);
app.run(['$ionicPlatform', '...other services...', function($ionicPlatform, ...other services...){
 
  function disableRipplePopup() {
    var dialogBody = parent.document.getElementById("exec-dialog");
    var overlay = parent.document.querySelector(".ui-widget-overlay");
    var ngDialog = angular.element(dialogBody.parentElement);
    var ngOverlay = angular.element(overlay);
    var hideRules = { "height": "0px", "width": "0px", "display": "none" };
    ngDialog.css(hideRules); // hide annoying popup
    ngOverlay.css(hideRules); // hide annoying popup's backdrop
  }
  
  $ionicPlatform.ready(function(){
    if(isRippleEmulator()) $timeout(disableRipplePopup);
  });

}])


```

**Comment by nsw2206** [comment]
thanks rodrigo. a thousand noobs will appreciate this :)
I know I do...  :+1:

**Comment by nsw2206** [comment]
two changes - add $timeout to the app.run line to avoid $timeout undefined and isRunningInRipple, not isRippleEmulator

app.run(function($ionicPlatform,$timeout) {
and 
 if(isRunningInRipple()) $timeout(disableRipplePopup);

**Comment by amilino** [comment]
I would remove display attribute, because it affects on your browser. Side effect is that you cannot for instance refresh page by pressing F5 in your browser or Ctrl+F5...

Before
`var hideRules = { "height": "0px", "width": "0px", "display": "none" };`

New
`var hideRules = { "height": "0px", "width": "0px" };`
