### ISSUE TITLE
phonegap build complains that it does not support v 1.0.3

### ISSUE THREAD

**Issue by ranjitpandit** [driftyco/ionic-plugins-keyboard#32]
It's great that v1.0.3 added support to show the keyboard on Android and it resolves a number of issues I was having. However, phonegap build is complaining that it does not support v1.0.3. 
Can you please fix that?

**Comment by ithav** [comment]
Hello,
Didn't want to open a new bug for it: seems like phonegap build does not any version > 1.0.3.
Is it a matter of submitting an new update? @adamdbradley 

Thanks in advance.
Ithav
