### ISSUE TITLE
Keyboard not showing on iPhone 6 Simulator

### ISSUE THREAD

**Issue by chaffeqa** [driftyco/ionic-plugins-keyboard#35]
Although it has worked once or twice, about 80% of the time when focusing an input:

![screenshot 2014-09-21 14 55 03](https://cloud.githubusercontent.com/assets/287640/4349729/2909ce48-41c1-11e4-808f-2f9c62a4afe0.png)

Don't have any iPhone 6's to test with, but this concerns me with whether its just the simulator.

Trying to dive in more, will update this issue if I find something.

**Comment by jasonshark** [comment]
this was tricky. Thank you for the answer

**Comment by max1me** [comment]
Helpul. Thanks

**Comment by ThinklabsGbR** [comment]
if this was a facebook-post, I would upvote this. @chaffeqa . Thx

**Comment by anupusergit2016** [comment]
This is correct solution.

**Comment by thewildandy** [comment]
You can now leave this setting checked if you also check "Toggle Software Keyboard" under the same menu, which will allow the device keyboard to pop up and accept input from your hardware keyboard.
