### ISSUE TITLE
Use on Windows causes app to not run 

### ISSUE THREAD

**Issue by stanzheng** [driftyco/ionic-plugins-keyboard#44]
Hi,

I know windows 8 is not supported but for windows 8 I'm getting this error which causes the device to load as a blank white screen and the app to not respond. 

my cordova build shows this as the error and I think the keyboard plugin is the issue for windows 8
```
The thread 0xae0 has exited with code 259 (0x103).
Error::Plugin not allowed in config.xml. Keyboard
The thread 0xc94 has exited with code 259 (0x103).
```

]

**Comment by oliversalzburg** [comment]
That error just indicates that the plugin wasn't loaded. It's not the cause for your issue.

**Comment by commonpike** [comment]
Ok .. yes, probably. Ofcourse, accessing cordova.plugins.Keyboard within javascript failed after that, causing my app to not initialize properly. I had to do a ```if  (cordova.plugins && cordova.plugins.Keyboard)``` around that block.

**Comment by stanzheng** [comment]
hi, i resolved my error.

That error was a red herring and the real error was an issue with the version of angular I had, had a routing bug.
