### ISSUE TITLE
keyboard height is incorrect, includes the statusbar height within

### ISSUE THREAD

**Issue by BarTsouri** [driftyco/ionic-plugins-keyboard#47]
Hello all,

As you can understand this is not the expected behavior.
What I did to solve it was to 
1. send the whole visible view height (rootView.getWindowVisibleDisplayFrame(r); ). Lets call it DispHeight
2. keyboardHeight -= dispHeight - window.innerHeight

Hope it helps anyone

**Comment by fragphace** [comment]
Hi,

Same problem here. On my Nexus 10 tablet with Android 4.4.2 `keyboardHeight` includes the statusbar height when config's fullscreen preference is set to `false`.  After I change fullscreen to `true` the height is correct.

It works ok on iPad with iOS 8.1.1.

**Comment by fernandopg** [comment]
This solution works with and without status bar https://github.com/driftyco/ionic-plugins-keyboard/pull/69

Hope it helps anyone!

**Comment by tlancina** [comment]
Fixed in https://github.com/driftyco/ionic-plugins-keyboard/commit/4682535c92f81557d64fa8b438339fdb043d07ef.
