### ISSUE TITLE
Can't find keyplane that supports type 5 for keyboard

### ISSUE THREAD

**Issue by softBarbarian** [driftyco/ionic-plugins-keyboard#48]
Hello,
I am seeing strange warning in my terminal logs while running my app with Keyboard plugin installed.
`Can't find keyplane that supports type 5 for keyboard iPhone-PortraitTruffle-PhonePad; using 3008722378_PortraitTruffle_iPhone-Complex-Pad_Default` 
It happends when I tap onto my input field `type='tel'` the number pad opens and app works fine but I thought I would ask.

Any idea what it means?

Thanks a lot.

**Comment by tlancina** [comment]
From what I can tell it seems to be an XCode or iOS Simulator bug.

**Comment by brnardo** [comment]
Hi,

this is happening for me too and the keyboard takes a while to show up.

**Comment by tlancina** [comment]
If you guys remove the plugin does the error go away?

**Comment by brnardo** [comment]
No it doesn't.

**Comment by tlancina** [comment]
So then it's not a keyboard plugin issue :)

**Comment by brnardo** [comment]
I also realized the bug wasn't introduced by the plugin update but it definitely didn't happen before.

Any idea on getting this fixed?

**Comment by tlancina** [comment]
Make sure iOS Simulator -> Hardware -> Keyboard -> Connect Hardware Keyboard is not checked.

**Comment by brnardo** [comment]
That did it, thanks a lot. I must have enable it doing some testing before and couldn't figure out it was the cause. Cheers!

**Comment by walkingriver** [comment]
I'm seeing this on the device itself (an iPhone 6), not the simulator.

**Comment by jackvial** [comment]
Seeing this on an iPhone 7

**Comment by idekterev** [comment]
Also seeing this on an iPhone 7 device. Not just an emulator issue. Any ideas anyone??

**Comment by peacepostman** [comment]
Iphone 7 too

**Comment by fanpyi** [comment]
It's only warning, We can don't care。

**Comment by Huang-Libo** [comment]
Same issue on iPhone 7 Plus

**Comment by yanglongji** [comment]
also iphone x
