### ISSUE TITLE
keyboard stock when plugin is installed / problems in simulator

### ISSUE THREAD

**Issue by Hirbod** [driftyco/ionic-plugins-keyboard#50]
When I use this plugin, the keyboard will take like 5-10 seconds on iPhone6 to show up the first time (maybe caused trough the native.event I'm look for)

After the first "boot up", the keyboards works fine and shows up immediatley.

Please guys, this is the only good keyboard plugin for Phonegap (because of the functions, events and especially the keyboardHeight) - but you need to support a bit more.

This plugins also break the keyboard on simulator. I'm quite not skilled enough on Objective-C to fix this kind of problems.

**Comment by tlancina** [comment]
Thanks for the issue, but I'm going to close this as I'm fairly certain it has nothing to do with the plugin.  On iOS the only thing the plugin does is listen for UIKeyboardWillShow and fires a JS event, which would not account for a 5-10 second slowdown.

As for breaking the simulator, it could be that you're using Ionic and have the hardware keyboard attached, which I have observed to break the scroll view resizing.  This is a bug that we're aware of (better hardware keyboard support).
