### ISSUE TITLE
Android: show keyboard with a proper type of it.

### ISSUE THREAD

**Issue by AleksMeshkov** [driftyco/ionic-plugins-keyboard#53]
When ```cordova.plugins.Keyboard.show();``` is called the plugin loads the text keyboard regardless of an input type.

For instance if an input has type set to ```tel``` the plugin should show us only the numeric keyboard.

**Comment by adnida** [comment]
+1

**Comment by jvelo** [comment]
FWIW I don't think there's a way to do that in Android without either having a native input, or emulating a native touch on the input in the WebView (calling .focus() in JS will focus the field but won't pop the keyboard). I had the need to programmatically pop a numeric soft keyboard, so I went for the later and created a plugin that focuses an elements as if the user would have tapped on it : https://github.com/46cl/cordova-android-focus-plugin/. This could be used as a basis to implement this behavior in the keyboard plugin.

**Comment by YanPelletier** [comment]
+1

**Comment by tlancina** [comment]
Closing as a dup of https://github.com/driftyco/ionic-plugins-keyboard/issues/45.
