### ISSUE TITLE
Support BlackBerry 10

### ISSUE THREAD

**Issue by compelab** [driftyco/ionic-plugins-keyboard#55]
Hi,

  I would like to provide a patch for this plugin to support BlackBerry 10. Is there any interest for this? I will do this in conjunction with @https://github.com/FelipeGualberto.

  Please, confirm.

Thanks,
Leandro.

**Comment by tlancina** [comment]
Fixed in https://github.com/driftyco/ionic-plugins-keyboard/commit/2190f4f11693e6e9b43ae47947d7c907287388aa.  Thanks again!
