### ISSUE TITLE
keyboardheight not correct on Huawei P6

### ISSUE THREAD

**Issue by BugHunter2k** [driftyco/ionic-plugins-keyboard#56]
testing on a HUAWEI P6-U06 reports keyboardHeight with 177px (Android Keyboard, and 180px Huawai Keyboard) both values are wrong. 
The height should be approximate 50px larger than reported by the event.

Does this only happen to me?

**Comment by tlancina** [comment]
Fixed in https://github.com/driftyco/ionic-plugins-keyboard/commit/4682535c92f81557d64fa8b438339fdb043d07ef.
