### ISSUE TITLE
Force soft keyboard

### ISSUE THREAD

**Issue by Urbiwanus** [driftyco/ionic-plugins-keyboard#57]
If a physical keyboard is attached to an Android Device, like a barcode scanner, the soft keyboard does not appear until you disable the physical keyboard. 

It would be great to have control over the soft keyboard even a physical one is connected. 

Regards

**Comment by tlancina** [comment]
Hey this would be cool, but looking into it it unfortunately doesn't seem possible from the scope of this plugin.

Not sure how well this works on all devices, but you can go to Settings --> Language & Input and either "turn off" the hardware keyboard when it is connected to show the soft keyboard (the hardware keyboard will still work), or in Lollipop devices, set "Show input method" to get the soft keyboard to show.
![image](https://cloud.githubusercontent.com/assets/804331/6581604/0da5b0c8-c726-11e4-9453-14b6666ae266.png)

Closing this as a wontfix for now.
