### ISSUE TITLE
Input box not reflecting input until loss of focus on Android

### ISSUE THREAD

**Issue by morinted** [driftyco/ionic-plugins-keyboard#66]
## Hardware and Software.

This problem is hard to reproduce, but occurs most reliably on a Nexus 5 running Lollipop. Other devices and OS versions see the error, but it seems like a the Nexus 7 is not prone.

## Description of the Problem

Android devices sometimes doesn't show the user input in input boxes until blur.

## Steps to Reproduce

1. The project must have Ionic keyboard installed.

2. You should be able to recreate this with a rather large page.

    A good way to induce the bug is to add load to the page. For example, a large image (1000px+) reduced to 100% width, some DIVs with content on an ng-show attached to models that your input box is modifying.

3. You can put multiple input boxes on the page, as it doesn't always occur.

4. Start the application, and quickly tap on an input box, and type in it. If the behavior is as expected, keep tapping other input boxes and typing. Eventually, you should see that as you type, your input is not being reflected in the input box (no characters, or no 'password bullets'), but the DOM is still reacting to the model.

5. Once you click away from that unresponsive box, the view will refresh and the input will be visible.

**Comment by tlancina** [comment]
Hey thanks for the detailed bug report! This sounds like an Ionic bug, since the plugin really just fires events in the webview.  If it's pressing, try opening an issue over at https://github.com/driftyco/ionic/issues, otherwise I will be giving the keyboard plugin and corresponding Ionic code a facelift soon.

**Comment by morinted** [comment]
Thanks @tlancina, the issue is resolved when removing the keyboard plug in, but I did initially suspect Ionic because it only cropped up after an upgrade to beta 14. I will eagerly await the facelift!
