### ISSUE TITLE
keyboard and crosswalk

### ISSUE THREAD

**Issue by alizarion** [driftyco/ionic-plugins-keyboard#70]
hi,

I recently started using ionic with Crosswalk , until version 8 of Crosswalk everything seems to work fine, since version 9 I have this strange behavior of the keyboard.

- without crosswalk: http://youtu.be/zG5qjMoO8Wg8
- with crosswalk: http://youtu.be/vJu-1jq76KY16

**Comment by tlancina** [comment]
Interesting, does it still do that if you remove the keyboard plugin?

**Comment by alizarion** [comment]
Yes, nothing changes, when i remove the plugin.
for more for details.

windowSoftInputMode:adjustResize => bug
windowSoftInputMode:adjustPan => OK but input is hidden by the keyboard.

in version 9 of Crosswalk, the bug [keycode is always zero](http://stackoverflow.com/questions/17139039/keycode-is-always-zero-in-chrome-for-android) has been fixed, can it have a relationship with this issue.

**Comment by tlancina** [comment]
Ok, so it's probably not a keyboard plugin issue then :) You could try forum.ionicframework.com or StackOverflow to see if anyone else has had similar issues.
