### ISSUE TITLE
Moving between inputs on iOS causes Hide Event

### ISSUE THREAD

**Issue by leandroz** [driftyco/ionic-plugins-keyboard#71]
Hey! I am listening to the show and hide events for modifying the bottom property of my scrollable area and for elements that needs to move with the Keyboard. On Android is working perfectly, but on iOS if you have more that one input and you change the focus between them, the Hide event is trigger and then the Show event instead of continue opened.
iOS 8 on an iPhone 6 real device.

**Comment by tlancina** [comment]
Thanks for the bug report! I'm pretty sure this is an Ionic bug and not a keyboard plugin issue, so I've opened a new issue over there.

**Comment by cortexml** [comment]
Any updates on this?
