### ISSUE TITLE
Footer rides up when losing focus.

### ISSUE THREAD

**Issue by flash20** [driftyco/ionic-plugins-keyboard#77]
Is there a way that when an input box loses its focus that the page footer doesn't sit on top the closing keyboard before jumping to the foot of the page?

The footer works fine if the user clicks on the 'done' button on the keyboard but if the user clicks anywhere on the page outside the input box the footer rides on top of the keyboard.

Can anyone help with this?

**Comment by jmfryan** [comment]
Did you find a solution to this? we are experiencing it too.
